version: "3.7"

services:
  db:
    image: mysql:8.0
    container_name: task-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_mysql
      MYSQL_USER: apiserver
      MYSQL_PASSWORD: apipassword
      TZ: Asia/Tokyo
    volumes:
      # - ./db/setup:/docker-entrypoint-initdb.d
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db.volume:/var/lib/mysql
    # command: mysqld --default-authentication-plugin=mysql_native_password

volumes:
  db.volume:
    name: db.volume
